### ISSUE TITLE
添加ECE 313 Spring2024

### ISSUE THREAD

**Issue by hmnkapa** [ZJUIntl-share/zjuintl-icicles#7]
[SP24_ECE313](https://github.com/user-attachments/files/17354784/SP24_ECE313.zip)
这是ECE 313 Spring2024（Prof. 陈飘）的课程内容，包含作业和作业答案、小测及答案、部分期中卷和往年卷
希望可以被添加到共享计划中🙏🏻🙏🏻🙏🏻

**Comment by geniucker-dev** [comment]
感谢贡献，已更新

https://icicles.zjuintl-share.top/ECE313/
